# Generated by Django 5.2 on 2025-04-30 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0006_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='image',
        ),
        migrations.AddField(
            model_name='banner',
            name='banner',
            field=models.ImageField(blank=True, default='', upload_to='assets/banners/%Y/%m'),
        ),
    ]
