# Generated by Django 5.2 on 2025-04-30 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0007_remove_banner_image_banner_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='banner',
        ),
        migrations.AddField(
            model_name='banner',
            name='banner_img',
            field=models.ImageField(blank=True, default='', upload_to='assets/banners/%Y/%m'),
        ),
    ]
