# Generated by Django 5.2 on 2025-05-01 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0008_remove_banner_banner_banner_banner_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menulink',
            name='new_tab',
        ),
    ]
