# Generated by Django 5.2 on 2025-05-01 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0009_remove_menulink_new_tab'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesetup',
            name='show_description',
        ),
        migrations.RemoveField(
            model_name='sitesetup',
            name='show_footer',
        ),
        migrations.RemoveField(
            model_name='sitesetup',
            name='show_header',
        ),
        migrations.RemoveField(
            model_name='sitesetup',
            name='show_menu',
        ),
        migrations.RemoveField(
            model_name='sitesetup',
            name='show_pagination',
        ),
        migrations.RemoveField(
            model_name='sitesetup',
            name='show_search',
        ),
    ]
