# Generated by Django 5.2 on 2025-05-02 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0010_remove_sitesetup_show_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
    ]
