# Generated by Django 5.2 on 2025-05-02 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0011_banner_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='description',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
