# Generated by Django 5.2 on 2025-05-02 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0012_alter_banner_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubMenuLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('site_setup', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submenu_link', to='site_setup.sitesetup')),
            ],
            options={
                'verbose_name': 'Sub Menu',
                'verbose_name_plural': 'Sub Menus',
            },
        ),
    ]
