# Generated by Django 5.2 on 2025-05-02 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0013_submenulink'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submenulink',
            options={'verbose_name': 'Sub Menu(Products)', 'verbose_name_plural': 'Sub Menus (Products)'},
        ),
    ]
