# Generated by Django 5.2 on 2025-05-02 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0014_alter_submenulink_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='submenulink',
            name='url_or_path',
            field=models.CharField(default=None, max_length=2048),
        ),
    ]
