# Generated by Django 5.2 on 2025-05-05 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0015_submenulink_url_or_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetup',
            name='background',
            field=models.ImageField(blank=True, default='', upload_to='assets/background/%Y/%m'),
        ),
    ]
