# Generated by Django 5.2 on 2025-05-05 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0016_sitesetup_background'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesetup',
            name='background',
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='background_image',
            field=models.ImageField(blank=True, default='', upload_to='assets/background/%Y/%m'),
        ),
    ]
