# Generated by Django 5.2 on 2025-05-05 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0017_remove_sitesetup_background_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesetup',
            name='background_image',
        ),
    ]
