# Generated by Django 5.2 on 2025-05-07 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0018_remove_sitesetup_background_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='button_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
