# Generated by Django 5.2 on 2025-05-07 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0019_banner_button_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='button_link',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
