# Generated by Django 5.2.1 on 2025-05-13 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0020_banner_button_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetup',
            name='whatsapp_message',
            field=models.CharField(default=False, help_text='Mensagem que será pré-preenchida quando o cliente clicar.', max_length=255, verbose_name='Mensagem automática do WhatsApp'),
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='whatsapp_number',
            field=models.CharField(default=False, help_text='Inclua o código do país', max_length=25, verbose_name='Número do Whatsapp'),
        ),
    ]
