# Generated by Django 5.2.1 on 2025-05-13 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0022_alter_sitesetup_whatsapp_message_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesetup',
            options={'verbose_name': 'Setup', 'verbose_name_plural': 'Setups'},
        ),
        migrations.AlterField(
            model_name='sitesetup',
            name='whatsapp_message',
            field=models.CharField(help_text='Mensagem que será pré-preenchida quando o cliente clicar.', max_length=255, verbose_name='Mensagem automática do WhatsApp'),
        ),
        migrations.AlterField(
            model_name='sitesetup',
            name='whatsapp_number',
            field=models.CharField(help_text='Inclua o código do país', max_length=25, verbose_name='Número do Whatsapp'),
        ),
    ]
