# Generated by Django 5.2.1 on 2025-05-13 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0023_alter_sitesetup_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesetup',
            name='whatsapp_message',
        ),
        migrations.RemoveField(
            model_name='sitesetup',
            name='whatsapp_number',
        ),
    ]
