# Generated by Django 5.2.1 on 2025-05-13 20:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0024_remove_sitesetup_whatsapp_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetup',
            name='whatsapp_message',
            field=models.CharField(default='', help_text='Mensagem que será pré-preenchida quando o cliente clicar.', max_length=255, verbose_name='Mensagem automática do WhatsApp'),
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='whatsapp_number',
            field=models.CharField(default='', help_text='Inclua o código do país', max_length=25, validators=[django.core.validators.RegexValidator(message='Digite apenas números, com ou sem + . Ex: +5521999999999', regex='^\\+?\\d+$')], verbose_name='Número do Whatsapp'),
        ),
    ]
