# Generated by Django 5.2.1 on 2025-05-13 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0025_sitesetup_whatsapp_message_sitesetup_whatsapp_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetup',
            name='whatsapp_icon',
            field=models.ImageField(default='', upload_to='assets/whatsapp_icon/%Y/%m/'),
        ),
    ]
