# Generated by Django 5.2.1 on 2025-05-24 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0028_alter_banner_banner_img_alter_banner_button_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordem'),
        ),
    ]
