# Generated by Django 5.2.1 on 2025-05-26 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0029_alter_banner_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetup',
            name='background_image',
            field=models.ImageField(default='', upload_to='assets/background/%Y/%m', verbose_name='Background Imagem'),
        ),
    ]
