# Generated by Django 5.2.1 on 2025-05-31 23:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0030_sitesetup_background_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesetup',
            name='whatsapp_icon',
        ),
        migrations.RemoveField(
            model_name='sitesetup',
            name='whatsapp_message',
        ),
        migrations.RemoveField(
            model_name='sitesetup',
            name='whatsapp_number',
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(default='', max_length=255, verbose_name='Horário')),
                ('telephone_number', models.CharField(default='', max_length=55, verbose_name='Número Telefone Fixo')),
                ('email', models.CharField(default='', max_length=65, verbose_name='Email')),
                ('whatsapp_number', models.CharField(default='', help_text='Inclua o código do país', max_length=25, validators=[django.core.validators.RegexValidator(message='Digite apenas números, com ou sem + . Ex: +5521999999999', regex='^\\+?\\d+$')], verbose_name='Número do Whatsapp')),
                ('instagram_url', models.URLField(default='', verbose_name='Instagram')),
                ('facebook_url', models.URLField(default='', verbose_name='Facebook')),
                ('whatsapp_icon', models.ImageField(default='', upload_to='assets/whatsapp_icon/%Y/%m/', verbose_name='Icone Whatsapp')),
                ('site_setup', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='site_setup.sitesetup')),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contatos',
            },
        ),
    ]
