# Generated by Django 5.2.1 on 2025-06-01 01:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0031_remove_sitesetup_whatsapp_icon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='whatsapp_icon',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='whatsapp_number',
        ),
        migrations.AddField(
            model_name='contacts',
            name='address_bonsucesso',
            field=models.CharField(default='', max_length=155, verbose_name='Endereço Bonsucesso'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='address_saocristovao',
            field=models.CharField(default='', max_length=155, verbose_name='Endereço São Cristóvão'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='whatsapp_number_footer',
            field=models.CharField(default='', max_length=25, verbose_name='Número do Whatsapp para Footer'),
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='whatsapp_icon',
            field=models.ImageField(default='', upload_to='assets/whatsapp_icon/%Y/%m/', verbose_name='Icone Whatsapp'),
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='whatsapp_number',
            field=models.CharField(default='', help_text='Inclua o código do país', max_length=25, validators=[django.core.validators.RegexValidator(message='Digite apenas números, com ou sem + . Ex: +5521999999999', regex='^\\+?\\d+$')], verbose_name='Número do Whatsapp'),
        ),
    ]
