# Generated by Django 5.2.1 on 2025-06-01 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0032_remove_contacts_whatsapp_icon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='telephone_number',
        ),
        migrations.AddField(
            model_name='contacts',
            name='telephone_number_bonsucesso',
            field=models.CharField(default='', max_length=55, verbose_name='Número Telefone Fixo(Bonsucesso)'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='telephone_number_saocristovao',
            field=models.CharField(default='', max_length=55, verbose_name='Número Telefone Fixo(São Cristóvão)'),
        ),
    ]
