# Generated by Django 5.2.1 on 2025-06-09 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0033_remove_contacts_telephone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='address_bonsucesso_link',
            field=models.CharField(default='', max_length=155, verbose_name='Endereço Bonsucesso Link'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='address_saocristovao_link',
            field=models.CharField(default='', max_length=155, verbose_name='Endereço São Cristóvão Link'),
        ),
    ]
