# Generated by Django 5.2.3 on 2025-08-10 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0034_contacts_address_bonsucesso_link_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submenulink',
            options={'verbose_name': 'Sub Menu(Produtos)', 'verbose_name_plural': 'Sub Menus (Produtos)'},
        ),
    ]
