# Generated by Django 5.2.3 on 2025-08-12 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0035_alter_submenulink_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submenulink',
            options={'verbose_name': 'Sub Menu(Produtos)', 'verbose_name_plural': 'Sub Menus(Produtos)'},
        ),
    ]
