# Generated by Django 5.2.5 on 2025-08-13 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0036_alter_submenulink_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submenulink',
            name='url_or_path',
            field=models.CharField(blank=True, default=None, max_length=248, null=True),
        ),
    ]
