# Generated by Django 5.2.5 on 2025-08-13 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0037_alter_submenulink_url_or_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='submenulink',
            name='url_or_path',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
