# Generated by Django 5.2.5 on 2025-08-20 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0038_alter_submenulink_url_or_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menulink',
            name='url_or_path',
            field=models.CharField(max_length=248),
        ),
    ]
