# Generated by Django 5.2.5 on 2025-08-20 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0039_alter_menulink_url_or_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='description',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='Descrição'),
        ),
    ]
