# Generated by Django 5.2.5 on 2025-09-11 19:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0040_alter_banner_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetup',
            name='whatsapp_number',
            field=models.CharField(default='', help_text='Inclua o código do país', max_length=25, validators=[django.core.validators.RegexValidator(message='Digite apenas números, com ou sem +. Ex: +5521999999999', regex='^\\+?\\d+$')], verbose_name='Número do Whatsapp'),
        ),
    ]
