# Generated by Django 5.2.3 on 2025-08-03 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bancadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_description', models.TextField(max_length=255)),
                ('long_description', models.TextField()),
                ('image', models.ImageField(upload_to='image_products/%Y/%m/')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Bancada',
                'verbose_name_plural': 'Bancadas',
            },
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
