# Generated by Django 5.2.3 on 2025-08-03 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_bancadas_delete_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bancadas',
            name='image',
            field=models.ImageField(upload_to='image_products/%Y/%m/', verbose_name='Imagem do produto'),
        ),
        migrations.AlterField(
            model_name='bancadas',
            name='long_description',
            field=models.TextField(verbose_name='Descrição Longa'),
        ),
        migrations.AlterField(
            model_name='bancadas',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='bancadas',
            name='short_description',
            field=models.TextField(max_length=255, verbose_name='Descrição Curta'),
        ),
        migrations.AlterField(
            model_name='bancadas',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
