# Generated by Django 5.2.3 on 2025-08-04 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_bancadas_image_alter_bancadas_long_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('short_description', models.TextField(max_length=255, verbose_name='Descrição Curta')),
                ('long_description', models.TextField(verbose_name='Descrição Longa')),
                ('image', models.ImageField(upload_to='image_products/%Y/%m/', verbose_name='Imagem do produto')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('product_type', models.CharField(choices=[('bancadas', 'Bancadas'), ('gabinetes-armários-balcões', 'Gabinetes-Armários-Balcões'), ('estantes', 'Estantes'), ('prateleiras', 'Prateleiras'), ('carrinhos', 'Carrinhos'), ('sistema-exaustão', 'Sistema-Exaustão'), ('sob-medida', 'Sob-Medida')], max_length=50, verbose_name='Tipo de Produto')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.DeleteModel(
            name='Bancadas',
        ),
    ]
