# Generated by Django 5.2.3 on 2025-08-10 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_products_delete_bancadas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_type',
            field=models.CharField(choices=[('bancadas', 'Bancadas'), ('gabinetes', 'Gabinetes'), ('estantes', 'Estantes'), ('prateleiras', 'Prateleiras'), ('carrinhos', 'Carrinhos'), ('sistema-exaustao', 'Sistema Exaustão'), ('sob-medida', 'Sob Medida'), ('maquinarios-equipamentos', 'Maquinários e Equipamentos')], max_length=50, verbose_name='Tipo de Produto'),
        ),
    ]
