# Generated by Django 5.2.3 on 2025-08-10 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_products_product_type'),
        ('site_setup', '0035_alter_submenulink_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_setup.submenulink', verbose_name='Tipo de Produto'),
        ),
    ]
