# Generated by Django 5.2.3 on 2025-08-12 20:41

import django.db.models.deletion
import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_products_product_type'),
        ('site_setup', '0036_alter_submenulink_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=products.models.product_image_upload_path, verbose_name='Imagem do produto')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_setup.submenulink', verbose_name='Tipo de Produto')),
            ],
            options={
                'verbose_name': 'Produto(Setup)',
                'verbose_name_plural': 'Produtos(Setup)',
            },
        ),
    ]
