# Generated by Django 5.2.3 on 2025-08-12 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_productssetup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productssetup',
            name='image',
            field=models.ImageField(upload_to='image_product_setup/<function product_image_upload_path at 0x7f68022eade0>', verbose_name='Imagem do produto'),
        ),
    ]
