# Generated by Django 5.2.3 on 2025-08-13 16:16

import utils.image_upload_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_productssetup_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(upload_to=utils.image_upload_path.product_image_upload_path, verbose_name='Imagem do produto'),
        ),
        migrations.AlterField(
            model_name='productssetup',
            name='image',
            field=models.ImageField(upload_to=utils.image_upload_path.product_image_upload_path, verbose_name='Imagem do produto'),
        ),
    ]
