# Generated by Django 5.2.5 on 2025-08-13 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_products_image_alter_productssetup_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='slug',
        ),
        migrations.AddField(
            model_name='products',
            name='slug_product',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='productssetup',
            name='slug_category',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
