# Generated by Django 5.2.5 on 2025-08-13 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_products_slug_products_slug_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='slug_product',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Slug do Produto'),
        ),
        migrations.AlterField(
            model_name='productssetup',
            name='slug_category',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Slug da Categoria'),
        ),
    ]
