# Generated by Django 5.2.5 on 2025-08-13 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_products_slug_product_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productssetup',
            options={'ordering': ['product_type'], 'verbose_name': 'Produto(Setup)', 'verbose_name_plural': 'Produtos(Setup)'},
        ),
    ]
