# Generated by Django 5.2.5 on 2025-08-16 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_productssetup_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='long_description',
            field=models.TextField(default='Lorem ipsum dolor sit, amet consectetur adipisicing elit. Illo aliquid, dolorem ratione facere eligendi nisi quidem veritatis, id, eius ipsa doloremque deserunt corporis aliquam commodi placeat itaque! Suscipit, incidunt id.Lorem ipsum dolor sit, amet consectetur adipisicing elit. Illo aliquid, dolorem ratione facere eligendi nisi quidem veritatis, id, eius ipsa doloremque deserunt corporis aliquam commodi placeat itaque! Suscipit, incidunt id.', verbose_name='Descrição Longa'),
        ),
        migrations.AlterField(
            model_name='products',
            name='short_description',
            field=models.TextField(default='Lorem ipsum dolor sit, amet consectetur adipisicing elit. Illo aliquid, dolorem ratione facere ', max_length=255, verbose_name='Descrição Curta'),
        ),
    ]
