# Generated by Django 5.2.5 on 2025-08-17 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_products_long_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='long_description',
            field=models.TextField(verbose_name='Descrição Longa'),
        ),
        migrations.AlterField(
            model_name='products',
            name='short_description',
            field=models.TextField(max_length=255, verbose_name='Descrição Curta'),
        ),
    ]
