# Generated by Django 5.2.5 on 2025-08-22 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_products_product_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Products',
        ),
    ]
