# Generated by Django 5.2.5 on 2025-08-22 17:28

import django.db.models.deletion
import utils.image_upload_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_delete_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('short_description', models.TextField(max_length=255, verbose_name='Descrição Curta')),
                ('long_description', models.TextField(verbose_name='Descrição Longa')),
                ('image', models.ImageField(upload_to=utils.image_upload_path.product_image_upload_path, verbose_name='Imagem do produto')),
                ('slug_product', models.SlugField(blank=True, null=True, unique=True, verbose_name='Slug do Produto')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productssetup', verbose_name='Tipo de Produto')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
    ]
