# Generated by Django 5.2.5 on 2025-08-22 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='long_description',
            field=models.TextField(default='Lorem ipsum dolor sit amet consectetur adipisicing elit. Harum, fuga. Neque expedita nihil sint. Harum saepe atque facilis velit sunt, nihil ea reiciendis nulla et facere. Fugit tempore repellat maiores!Lorem ipsum dolor sit amet consectetur adipisicing elit. Harum, fuga. Neque expedita nihil sint. Harum saepe atque facilis velit sunt, nihil ea reiciendis nulla et facere. Fugit tempore repellat maiores!', verbose_name='Descrição Longa'),
        ),
        migrations.AlterField(
            model_name='products',
            name='short_description',
            field=models.TextField(default='Lorem ipsum dolor sit amet consectetur adipisicing elit. Harum, fuga. Neque expedita nihil sint.', max_length=255, verbose_name='Descrição Curta'),
        ),
    ]
