# Generated by Django 5.2.5 on 2025-09-07 17:30

import utils.image_upload_path
import utils.model_validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_alter_products_long_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productssetup',
            name='image',
            field=models.ImageField(upload_to=utils.image_upload_path.product_image_upload_path, validators=[utils.model_validator.validate_png], verbose_name='Imagem do produto'),
        ),
    ]
