# Generated by Django 5.2.5 on 2025-11-03 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_alter_productssetup_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SobMedidaProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image_sob_medida', models.ImageField(upload_to='portfolio_sob_medida/%Y/%m')),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Item do Portfólio',
                'verbose_name_plural': 'Itens do Portfólio',
                'ordering': ['order', 'title'],
            },
        ),
    ]
