# Generated by Django 5.2.5 on 2025-11-07 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_sobmedidaproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='SobMedidaPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título do Projeto')),
                ('image_sob_medida', models.ImageField(upload_to='portfolio_sob_medida/%Y/%m', verbose_name='Imagem do Projeto')),
                ('description', models.TextField(blank=True, verbose_name='Descrição Curta')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem de Exibição')),
            ],
            options={
                'verbose_name': 'Item do Portfólio(Sob Medida)',
                'verbose_name_plural': 'Itens do Portfólio(Sob Medida)',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SobMedidaRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('project_description', models.TextField(verbose_name='Descrição do Projeto')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='projetos_sob_medida/%Y/%m', verbose_name='Anexo (Planta/Desenho)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pedido Sob Medida',
                'verbose_name_plural': 'Pedidos Sob Medida',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='SobMedidaProject',
        ),
    ]
