# Generated by Django 5.2.5 on 2025-09-02 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budgetrequest',
            options={'verbose_name': 'Pedido de Orçamento', 'verbose_name_plural': 'Pedidos de Orçamentos'},
        ),
    ]
