# Generated by Django 5.2.1 on 2025-05-13 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300)),
                ('description', models.CharField(blank=True, default='', max_length=1000)),
                ('button_name', models.CharField(blank=True, max_length=50)),
                ('button_link', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, default='', upload_to='assets/featured_products/%Y/%m')),
            ],
            options={
                'verbose_name': 'Featured Product',
                'verbose_name_plural': 'Featured Products',
            },
        ),
    ]
