# Generated by Django 5.2.1 on 2025-05-24 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhyGazil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default='', max_length=1000)),
                ('icon', models.CharField(default='', max_length=10)),
            ],
            options={
                'verbose_name': 'Por que Gazil',
                'verbose_name_plural': 'Por que Gazil',
            },
        ),
        migrations.AlterModelOptions(
            name='featuredproducts',
            options={'verbose_name': 'Produto Destacado', 'verbose_name_plural': 'Produtos Destacados'},
        ),
    ]
