# Generated by Django 5.2.1 on 2025-05-24 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_whygazil_alter_featuredproducts_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='whygazil',
            name='title',
            field=models.CharField(default='', max_length=50, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='featuredproducts',
            name='button_link',
            field=models.CharField(blank=True, max_length=100, verbose_name='Button Link'),
        ),
        migrations.AlterField(
            model_name='featuredproducts',
            name='button_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Button Name'),
        ),
        migrations.AlterField(
            model_name='featuredproducts',
            name='description',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='featuredproducts',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='assets/featured_products/%Y/%m', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='featuredproducts',
            name='title',
            field=models.CharField(blank=True, max_length=300, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='whygazil',
            name='description',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='whygazil',
            name='icon',
            field=models.CharField(default='', max_length=10, verbose_name='Ícone'),
        ),
    ]
