# Generated by Django 5.2.1 on 2025-05-24 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_whygazil_title_alter_featuredproducts_button_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whygazil',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Descrição'),
        ),
    ]
