# Generated by Django 5.2.3 on 2025-06-28 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_contacts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='name',
        ),
        migrations.AddField(
            model_name='contacts',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
