# Generated by Django 5.2.3 on 2025-06-28 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_remove_contacts_name_contacts_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
    ]
