# Generated by Django 5.2.5 on 2025-09-11 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_socialaprovation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialaprovation',
            options={'ordering': ['-created_at'], 'verbose_name': 'Aprovação Social', 'verbose_name_plural': 'Aprovações Sociais'},
        ),
    ]
